{{if .Values.ingress.enabled}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  - host: {{index .Values.ingress.hosts 0 | default "rollouts-demo.local" }}
    http:
      paths:
      - path: /
        backend:
          # Reference to a Service name, also specified in the Rollout spec.strategy.canary.stableService field
          serviceName: {{ template "helm-guestbook.fullname" . }}
          servicePort: {{ .Values.service.port }}
{{end}}
